DEFAULT_STOCKS = [
    {'ticker': 'AAPL', 'company': 'Apple Inc.', 'sector': 'Core Technology'},
    {'ticker': 'MSFT', 'company': 'Microsoft Corp', 'sector': 'Core Technology'},
    {'ticker': 'NVDA', 'company': 'NVIDIA Corp', 'sector': 'Semiconductors'},
    {'ticker': 'AVGO', 'company': 'Broadcom Inc.', 'sector': 'Semiconductors'},
    {'ticker': 'AMD', 'company': 'Advanced Micro Devices', 'sector': 'Semiconductors'},
    {'ticker': 'ACN', 'company': 'Accenture plc', 'sector': 'IT Services'},
    {'ticker': 'ADBE', 'company': 'Adobe Inc.', 'sector': 'Software'},
    {'ticker': 'CRM', 'company': 'Salesforce Inc.', 'sector': 'Software'},
    {'ticker': 'ORCL', 'company': 'Oracle Corp', 'sector': 'Software'},
    {'ticker': 'CSCO', 'company': 'Cisco Systems', 'sector': 'Networking'},
    {'ticker': 'QCOM', 'company': 'Qualcomm Inc.', 'sector': 'Semiconductors'},
    {'ticker': 'NOW', 'company': 'ServiceNow Inc.', 'sector': 'Software'},
    {'ticker': 'INTC', 'company': 'Intel Corp', 'sector': 'Semiconductors'},
    {'ticker': 'IBM', 'company': 'International Business Machines', 'sector': 'IT Services'},
    {'ticker': 'AMAT', 'company': 'Applied Materials', 'sector': 'Semiconductor Equipment'},
    {'ticker': 'PLTR', 'company': 'Palantir Technologies', 'sector': 'Software'},
    {'ticker': 'PANW', 'company': 'Palo Alto Networks', 'sector': 'Cybersecurity'},
    {'ticker': 'LRCX', 'company': 'Lam Research', 'sector': 'Semiconductor Equipment'},
    {'ticker': 'MU', 'company': 'Micron Technology', 'sector': 'Semiconductors'},
    {'ticker': 'TXN', 'company': 'Texas Instruments', 'sector': 'Semiconductors'},
    {'ticker': 'INTU', 'company': 'Intuit Inc.', 'sector': 'Software'},
    {'ticker': 'ADI', 'company': 'Analog Devices', 'sector': 'Semiconductors'},
    {'ticker': 'ANET', 'company': 'Arista Networks', 'sector': 'Networking'},
    {'ticker': 'CDNS', 'company': 'Cadence Design Systems', 'sector': 'Software'},
    {'ticker': 'SNPS', 'company': 'Synopsys Inc.', 'sector': 'Software'},
    {'ticker': 'KLAC', 'company': 'KLA Corporation', 'sector': 'Semiconductor Equipment'},
    {'ticker': 'CRWD', 'company': 'CrowdStrike Holdings', 'sector': 'Cybersecurity'},
    {'ticker': 'DELL', 'company': 'Dell Technologies', 'sector': 'Hardware'},
    {'ticker': 'APP', 'company': 'AppLovin', 'sector': 'Software'},
    {'ticker': 'FTNT', 'company': 'Fortinet', 'sector': 'Cybersecurity'},
    {'ticker': 'ZS', 'company': 'Zscaler Inc.', 'sector': 'Cybersecurity'},
    {'ticker': 'NET', 'company': 'Cloudflare Inc.', 'sector': 'Cloud Infrastructure'},
    {'ticker': 'HPE', 'company': 'Hewlett Packard Enterprise', 'sector': 'Hardware'},
    {'ticker': 'HPQ', 'company': 'HP Inc.', 'sector': 'Hardware'},
    {'ticker': 'NXPI', 'company': 'NXP Semiconductors', 'sector': 'Semiconductors'},
    {'ticker': 'MCHP', 'company': 'Microchip Technology', 'sector': 'Semiconductors'},
    {'ticker': 'ON', 'company': 'ON Semiconductor', 'sector': 'Semiconductors'},
    {'ticker': 'ADSK', 'company': 'Autodesk Inc.', 'sector': 'Software'},
    {'ticker': 'V', 'company': 'Visa Inc.', 'sector': 'Payments'},
    {'ticker': 'MA', 'company': 'Mastercard Inc.', 'sector': 'Payments'},
    {'ticker': 'GPN', 'company': 'Global Payments', 'sector': 'Payments'},
    {'ticker': 'FIS', 'company': 'Fidelity National Information Services', 'sector': 'Fintech'},
    {'ticker': 'FI', 'company': 'Fiserv Inc.', 'sector': 'Fintech'},
    {'ticker': 'PAYX', 'company': 'Paychex Inc.', 'sector': 'Software'},
    {'ticker': 'PAYC', 'company': 'Paycom Software', 'sector': 'Software'},
    {'ticker': 'TYL', 'company': 'Tyler Technologies', 'sector': 'Software'},
    {'ticker': 'PTC', 'company': 'PTC Inc.', 'sector': 'Software'},
    {'ticker': 'FICO', 'company': 'Fair Isaac Corp', 'sector': 'Data & Analytics'},
    {'ticker': 'CTSH', 'company': 'Cognizant Technology Solutions', 'sector': 'IT Services'},
    {'ticker': 'CDW', 'company': 'CDW Corp', 'sector': 'IT Services'},
    {'ticker': 'EPAM', 'company': 'EPAM Systems', 'sector': 'IT Services'},
    {'ticker': 'IT', 'company': 'Gartner Inc.', 'sector': 'Research & Analytics'},
    {'ticker': 'VRSK', 'company': 'Verisk Analytics', 'sector': 'Data & Analytics'},
    {'ticker': 'VRSN', 'company': 'Verisign Inc.', 'sector': 'Internet Infrastructure'},
    {'ticker': 'AKAM', 'company': 'Akamai Technologies', 'sector': 'Internet Infrastructure'},
    {'ticker': 'FFIV', 'company': 'F5 Inc.', 'sector': 'Networking'},
    {'ticker': 'JNPR', 'company': 'Juniper Networks', 'sector': 'Networking'},
    {'ticker': 'MSI', 'company': 'Motorola Solutions', 'sector': 'Communications Equipment'},
    {'ticker': 'APH', 'company': 'Amphenol Corp', 'sector': 'Electronic Components'},
    {'ticker': 'TEL', 'company': 'TE Connectivity', 'sector': 'Electronic Components'},
    {'ticker': 'GLW', 'company': 'Corning Inc.', 'sector': 'Electronic Components'},
    {'ticker': 'KEYS', 'company': 'Keysight Technologies', 'sector': 'Electronic Equipment'},
    {'ticker': 'TDY', 'company': 'Teledyne Technologies', 'sector': 'Electronic Equipment'},
    {'ticker': 'TRMB', 'company': 'Trimble Inc.', 'sector': 'Technology Hardware'},
    {'ticker': 'ZBRA', 'company': 'Zebra Technologies', 'sector': 'Technology Hardware'},
    {'ticker': 'STX', 'company': 'Seagate Technology', 'sector': 'Storage Hardware'},
    {'ticker': 'WDC', 'company': 'Western Digital', 'sector': 'Storage Hardware'},
    {'ticker': 'ENPH', 'company': 'Enphase Energy', 'sector': 'Clean Technology'},
    {'ticker': 'SEDG', 'company': 'SolarEdge Technologies', 'sector': 'Clean Technology'},
    {'ticker': 'TER', 'company': 'Teradyne Inc.', 'sector': 'Semiconductor Equipment'},
    {'ticker': 'MPWR', 'company': 'Monolithic Power Systems', 'sector': 'Semiconductors'},
    {'ticker': 'SWKS', 'company': 'Skyworks Solutions', 'sector': 'Semiconductors'},
    {'ticker': 'GOOGL', 'company': 'Alphabet Inc. (Class A)', 'sector': 'Internet & Media'},
    {'ticker': 'GOOG', 'company': 'Alphabet Inc. (Class C)', 'sector': 'Internet & Media'},
    {'ticker': 'META', 'company': 'Meta Platforms Inc.', 'sector': 'Internet & Media'},
    {'ticker': 'NFLX', 'company': 'Netflix Inc.', 'sector': 'Internet & Media'},
    {'ticker': 'TMUS', 'company': 'T-Mobile US', 'sector': 'Telecommunications'},
    {'ticker': 'VZ', 'company': 'Verizon Communications', 'sector': 'Telecommunications'},
    {'ticker': 'T', 'company': 'AT&T Inc.', 'sector': 'Telecommunications'},
    {'ticker': 'EA', 'company': 'Electronic Arts', 'sector': 'Interactive Media'},
    {'ticker': 'TTWO', 'company': 'Take-Two Interactive', 'sector': 'Interactive Media'},
    {'ticker': 'MTCH', 'company': 'Match Group', 'sector': 'Internet & Media'},
    {'ticker': 'WBD', 'company': 'Warner Bros. Discovery', 'sector': 'Media'},
    {'ticker': 'CHTR', 'company': 'Charter Communications', 'sector': 'Telecommunications'},
    {'ticker': 'AMZN', 'company': 'Amazon.com Inc.', 'sector': 'Internet & Commerce'},
    {'ticker': 'TSLA', 'company': 'Tesla Inc.', 'sector': 'Technology-Adjacent'},
    {'ticker': 'BKNG', 'company': 'Booking Holdings', 'sector': 'Internet & Commerce'},
    {'ticker': 'EXPE', 'company': 'Expedia Group', 'sector': 'Internet & Commerce'},
    {'ticker': 'ABNB', 'company': 'Airbnb Inc.', 'sector': 'Internet & Commerce'},
    {'ticker': 'EBAY', 'company': 'eBay Inc.', 'sector': 'Internet & Commerce'},
    {'ticker': 'ETSY', 'company': 'Etsy Inc.', 'sector': 'Internet & Commerce'},
    {'ticker': 'AXON', 'company': 'Axon Enterprise', 'sector': 'Technology Hardware'},
    {'ticker': 'GE', 'company': 'GE Aerospace', 'sector': 'Industrial Technology'},
    {'ticker': 'HON', 'company': 'Honeywell International', 'sector': 'Industrial Technology'},
    {'ticker': 'ROK', 'company': 'Rockwell Automation', 'sector': 'Industrial Technology'},
    {'ticker': 'SPGI', 'company': 'S&P Global', 'sector': 'Data & Analytics'},
    {'ticker': 'MCO', 'company': "Moody's Corp", 'sector': 'Data & Analytics'},
    {'ticker': 'MSCI', 'company': 'MSCI Inc.', 'sector': 'Data & Analytics'},
    {'ticker': 'FDS', 'company': 'FactSet Research Systems', 'sector': 'Data & Analytics'},
    {'ticker': 'EFX', 'company': 'Equifax Inc.', 'sector': 'Data & Analytics'},
    {'ticker': 'TRU', 'company': 'TransUnion', 'sector': 'Data & Analytics'},
]
