name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Or your main development branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Changed to ubuntu-latest for broader compatibility, ubuntu:25.04 might be too specific or not readily available as a GitHub Actions runner image.

    permissions: # Add permissions for packages:write to push to GHCR
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- Frontend (Vue.js) Build ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.1.0' # Or your preferred Node.js version

      - name: Install Frontend Dependencies
        working-directory: ./frontend # Assuming your Vue.js project is in a 'frontend' folder
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # --- Backend (Java) Build ---
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Or 'adopt', 'zulu', etc.
          java-version: '21' # Or your project's Java version

      - name: Build Backend with Maven # Or Gradle, depending on your build tool
        working-directory: ./backend # Assuming your Java project is in a 'backend' folder
        run: mvn clean install # Use -DskipTests if you have separate test jobs or want to skip for now

      # --- Dockerization with GHCR ---
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend # Path to your frontend Dockerfile
          push: true
          # Tags format for GHCR: ghcr.io/<YOUR_GITHUB_USERNAME>/<REPOSITORY_NAME>-<IMAGE_NAME>:<TAG>
          tags: ghcr.io/${{ github.repository_owner }}/stockifyai-frontend:latest
          # You can also add more specific tags, e.g., ghcr.io/${{ github.repository_owner }}/stockifyai-frontend:${{ github.sha }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend # Path to your backend Dockerfile
          push: true
          # Tags format for GHCR: ghcr.io/<YOUR_GITHUB_USERNAME>/<REPOSITORY_NAME>-<IMAGE_NAME>:<TAG>
          tags: ghcr.io/${{ github.repository_owner }}/stockifyai-backend:latest
          # You can also add more specific tags, e.g., ghcr.io/${{ github.repository_owner }}/stockifyai-backend:${{ github.sha }}

      # --- Deployment (Example - this will vary greatly based on your setup) ---
      # This is a placeholder. You might use actions for deploying to Kubernetes,
      # cloud providers (AWS, Azure, GCP), etc.
      # - name: Deploy Application
      #  run: |
       #   echo "Deployment steps go here..."
          # Example: kubectl apply -f kubernetes/deployment.yaml
          # Example: aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment